cache:
  type: simple

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

kafka:
  bootstrap-servers: localhost:9092

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 1000
  genres:
    read-timeout: 1000
  videos:
    read-timeout: 1000
  keycloak:
    read-timeout: 1000

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 300

resilience4j.retry:
  configs:
    default:
      maxAttempts: 2
      waitDuration: 100