keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  host: ${KEYCLOAK_HOST:http://keycloak.internal:8443}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}

rest-client:
  base-url: http://localhost:8080
  keycloak:
    read-timeout: 1_000

# o profle de dev eh o mais simples possivel, sem muitas das integracoes  que o projeto possui
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration