keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

logging:
  level:
    ROOT: info

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  keycloak:
    read-timeout: 1000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:subscription_test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2